### PR TITLE
negated angular-placeholders-0.0.1-SNAPSHOT.min.js from .gitignore file

### PR DESCRIPTION
**Pull request by jamesbrink**
This is to address the placeholder issue when migrating this boilerplate into another project. I realize that file has been out there for a while now, this is just a band aide to keep people from getting this fun surprise. 

Reference #198, #120 and #322 

Maybe we could just get this included into the boilerplate until the root issue is resolved.

### CODE REVIEW

**Comment by RoboSparrow** [comment]
+1

**Comment by RoboSparrow** [comment]
+1

**Comment by jamesbrink** [comment]
Anyone want to possibly close or merge this?

**Comment by jamesbrink** [comment]
closing this due to inactivity

**Pull request closed without merging**
