### PR TITLE
Removing obnoxious comments

### PR DESCRIPTION
**Pull request by oatkiller**
This is probably the kind of thing that alienates so many non-bros from programming.

### CODE REVIEW

**Comment by joshdmiller** [comment]
I appreciate the feedback. I'm always looking for ways to make more people feel welcome. I have two thoughts here.

First, ngbp is _opinionated_, so I'm okay saying that it was designed with what the project contributors consider best practices in mind.

Second, TDD is hugely valuable to ng developers, particularly those who are new to the framework. Part of the reason is the documentation shortcoming; it's easy to find out how to do small things with ng, but a lot harder to ensure we're getting the "big picture" concepts right. One of the areas where most improvement is needed is in separation of concerns. TDD specifically ensures that components were properly isolated, because if they were not then the test cannot be written (or at least not easily).

All that said, I have no specific _objection_ to this change; you kept the same conversant, friendly style the rest of the readme follows and the information certainly is in no way wrong.

If the community likes the change, I'll merge it. :-)

**Comment by eomuraliev** [comment]
:+1:

**Comment by PaulL1** [comment]
I didn't mind it the way it originally was - I think the irreverent humour / opinionation is a big part of what makes ngbp what it is.  I don't think people really believe you when you say things like that.  I also don't mind the update, and I guess the project might have to present a more mature facade at some point.

Given @oatkiller went to the effort of making a PR, I'd merge it.

**Comment by joelhooks** [comment]
The update is fine. 

I was trying to figure out what the original text has to do with "bro" language. 

TDD as an absolute essential is something I associate with XP (extreme programming) and gray hair. People that have been writing production code for 30 years and have learned the hard way. 

Open source sometimes feels like death by 1000 cuts. 

Thanks Josh, your project has been a huge help to me. I appreciate it.

**Pull request closed without merging**
