### PR TITLE
Test case for uglify

### PR DESCRIPTION
**Pull request by PaulL1**
Looks to me like the http interceptor is causing it in my case.  I don't have time this morning before work to look through and understand what might be causing it about this interceptor, but I reckon it'll be the format I've used for declaring something - I copied this logic off some random web page, and it always worked so I never went back to look more closely at it.

In case you don't feel like pulling the whole thing, the relevant module is:

```
/**
 * Authentication module, redirects to homepage if not logged in 
 */

angular.module('common.authentication', [
  ])

.config(function( $httpProvider ){
  // Intercepts every http request.  If the response is success, pass it through.  If the response is an
  // error, and that error is 401 (unauthorised) then the user isn't logged in, redirect to the login page 
  var interceptor = function( $q, $rootScope ) {
    return {
      'responseError': function(rejection) {
        if ( rejection.status == 401 ) {
          $rootScope.$broadcast('event:unauthorized');

          return $q.reject(rejection);
        }
        return $q.reject(rejection);        
      }
    };
  };
  $httpProvider.interceptors.push(interceptor);
})
;
```

And the error I get when running it after uglification is:

```
Uncaught Error: [$injector:unpr] Unknown provider: aProvider <- a <- $http <- $compile
```

### CODE REVIEW

**Comment by PaulL1** [comment]
I suspect the correct change here relates to the interceptor function:

```
 var interceptor = function( $q, $rootScope ) {
```

changes to

```
 var interceptor = ['$q', '$rootScope', function( $q, $rootScope ) {
```

I'll take a look at it this evening, but I think I'm basically making the exact mistake that @SailingYYC mentioned.

I have other instances in my code that I'll look at tonight that are more in the format:

```
.factory('BreadcrumbService', function( $state, $rootScope ) {
```

I think that ngMin deals with these (and the documentation has some support for that position: https://github.com/btford/ngmin), but again I'll check that tonight.

**Comment by joshdmiller** [comment]
There are a lot of commits here. @PaulL1 - can you bring me up to speed here?

**Comment by PaulL1** [comment]
You had sought a test case for an example where ngMin doesn't work, this is a test case.  But the short answer is that you were right, I had one function in my code that didn't follow the required syntax for ngMin, the change I describe in my last comment is the one that fixes the issue, on that basis there is nothing to add and nothing to commit, just a sample in case you wanted to look at it (don't see why you'd want to).

The set of commits relate to something we discussed a while back - I didn't correctly branch my original commit, so that means that everything I've submitted is baselined from that same commit - all my e2e testing stuff has ended up in this example, although it really isn't related to it.

I'd close this (and I thought I had).  On the basis that I opened it, assuming it's OK for me to also close it.

**Comment by joshdmiller** [comment]
Ah, I remember now. I am going through the ever-increasing backlog of
issues and closing everything that's no longer relevant or is invalid or
has been fixed already and I didn't remember what this one was all about,
but I've rejoined the pack now.

Glad it's all resolved!

**Pull request closed without merging**
