### PR TITLE
Append pkg.version to compiled js and css files.

### PR DESCRIPTION
**Pull request by sudhakar**
Now browsers can cache them aggresively. After every major change simply bump your pkg.version to push the new assets to the clients.

### CODE REVIEW

**Comment by sudhakar** [comment]
I am still pretty new to GIT stuff..
Let me know if you need any changes to the commit.

**Comment by joshdmiller** [comment]
Looks good to me. I'll add this to the list for the next patch release (in a few days).

**Comment by cymantic** [comment]
Is it not better to put the pkg version against the assets directory, so that all assets can be aggresively cached?

i.e. I would have:

```
/assets-1.2.3/ng-boilerplate.css
/assets-1.2.3/ng-boilerplate.js
/assets-1.2.3/splash-image.png
```

**Comment by joshdmiller** [comment]
@cymantic Not necessarily. If you keep versioned assets inside `assets/` then they should have their own versioning scheme. As far as ngBoilerplate is concerned, however, it only needs to version the files it manages. For example, why break caching during every minor update on the large assets like images when they probably never changed?

**Comment by cymantic** [comment]
@joshdmiller yes, fair enough.

Thinking of other use cases where lots of assets are involved (e.g. e-commerce, forums, portals...) I think most image assets would be handled outside of angular application, with only the core application assets (i.e. not product images, article images etc...) in `src/assets`.

For the cases where I may want to version the entire assets directory I can change the boilerplate.

Keep the boilerplate set up for the majority of use cases. It is a fantastic starting point.

**Comment by joshdmiller** [comment]
Landed as 90e1b71. Thanks, @sudhakar!

**Pull request closed without merging**
