### PR TITLE
Karma.unit.port

### PR DESCRIPTION
**Pull request by roychoo**
changing the runnerPort to use port instead in `Gruntfile.js`
as `configure` is deprecated, changing to use `set` instead

### CODE REVIEW

**Comment by ToucheSir** [comment]
Beat me too it :D. Just a couple little nitpicky things, however. I believe the grunt-karma needs updating in package.json, and the port should preferably be 9019 (to maintain consistency with <code>karma:continuous</code>).

**Comment by roychoo** [comment]
@ToucheSir done :)

**Comment by ToucheSir** [comment]
:)

**Comment by ToucheSir** [comment]
@joshdmiller I was beaten to it...are you still planning to make a patch release for this?

**Comment by eladmoshe** [comment]
I think this one is a critical pull request. It fixes my issue #193.

**Comment by dillonforrest** [comment]
+1 this needs to be merged :)

**Comment by jboothe** [comment]
+1 on merge

**Comment by albertboada** [comment]
+1

**Comment by joshdmiller** [comment]
Fixed as part of a larger Karma update. Thanks for fixing!

**Pull request closed without merging**
