### PR TITLE
update ngbp to use latest available tools and packages

### PR DESCRIPTION
**Pull request by mbroadst**
This branch is labeled "update-angular", because the initial intent was to update to angular 1.3, however, it ended up being a general "update ngbp" instead. As a result, I propose the included change to bump the version to 0.3.2.

### CODE REVIEW

**Comment by 0x6a68** [comment]
https://github.com/bower/bower/issues/1102

**Comment by mbroadst** [comment]
@johannestroeger updated to require bower 1.2.8, I assume that's what you were getting at here?

**Comment by 0x6a68** [comment]
ok. now add a semicolon please :dart:

**Comment by mbroadst** [comment]
doh, updated. :)

**Comment by 0x6a68** [comment]
:+1: it passed

**Comment by elhigu** [comment]
Awesome, works great! However Bootstrap is still 2.x version. Any plans to update also to bootstrap 3?

**Comment by mbroadst** [comment]
I was hoping that the pull request would be merged in before I did that as well. I have updated bootstrap to 3.x on my local system, but it makes the PR all the harder to accept when there's so much going on. Having said that, it's been over two weeks with no response from the project.. so it may be worth just going ahead and updating that as well

**Comment by elhigu** [comment]
Looking forward to it. Hopefully someone who is interested to keep this up-to-date will start fork from this, where necessary pull requests could be merged.

**Comment by 108adams** [comment]
I did upgrade by myself as well, for Angular too. I cannot handle the fork
by myself, but can help if there is a fork.

Adam
28-03-2014 14:16, "Mikael Lepistö" notifications@github.com napisał(a):

**Comment by svycka** [comment]
maybe this one https://github.com/kvindasAB/angular-enterprise-kickstart

**Comment by dv336699** [comment]
@svycka thanks, I think that it's time to move on, sadly the project seems to be dead. last commit was 4 months ago.

**Comment by joshdmiller** [comment]
There was way too much going on in this PR to merge all at once. It also started clashing with other PRs because of the broad scope of changes. :-)

However, all of these changes have been merged _incrementally_ across several different commits in the v0.3.2-wip branch which will become the default branch once I finish merging PRs. Thanks!!!

FYI, @diego-vieira - It's been very slow-going as I've been super busy with work and a lot of people have made the same observation about how long ago the last commit was. However, it's not true. The last commit on the _default branch_ was 4 months ago, but that's because it's a release branch - there will never be any commits there. If you look at the other branches, there have been many commits over the last few months, mostly for the rewrite. But in either event, I agree that PRs sat around for far too long.

**Pull request closed without merging**
