### PR TITLE
feat(cli): Command-line interface enhanced a lot

### PR DESCRIPTION
**Pull request by joshdmiller**
The CLI logic has been migrated from ngbp-cli to here in order to decrease the need to constantly update ngbp-cli with the changes of ngbp proper. ngbp-cli is now a thin wrapper for calling the CLI methods of ngbp proper.

As such, most of this commit adds CLI functionality from ngbp-cli, enhances it, adds error checking, and implements new help features.

In order to accommodate the CLI logic, there are several significant changes to ngbp. A new "log" module was added to do consistent logging, but the existing codebase has _not_ been adapted to use it yet. To make CLI options available globally, a new "options" module was created. To check for a local ngbp installation more easily, the "index" of the module was moved from "index.js" to "lib/ngbp.js" and all ngbp modules were moved from "lib" to "lib/ngbp".

Lastly, to accommodate being launched either from Grunt or from the new ngbp-cli, ngbp now calls Grunt internals directly, but will only bootstrap itself automatically if launched from Grunt. This way, ngbp can work through the ngbp-cli, programmatically through any library that calls it, or through Grunt simply by any of the ngbp grunt tasks loading the ngbp module.

### CODE REVIEW

**Comment by PaulL1** [comment]
A lot more to review here.  I've submitted a pull again (#214) with minor formatting stuff, at this stage not much value add but a first pass through of syntax and questions.

Questions:
1. cli.js line 136 or thereabouts.  I can't work out what cb() is - it's a rather obscure name, it looks like a function that would be in the files hash that was passed in, but the comment doesn't say anything about calling a function against each file
2. For config.js, it feels like we might want to have new config values associated with a particular plugin/contrib.  I think the structure we have would have a set of config centrally (in this config.js), and then a particular plugin might have it's own, additional, config file.  This is tidy, but it feels like it might be more flexible to have a pluggable config setup - maybe for example each plugin/contrib can have its own config file with a specified name/location, and we'd concatenate and de-duplicate.  This might let a "family" of plugins share config values
3.  I resisted the temptation to change colors to colours.  :-).  I was mildly amused at the comment designating our users as "she" in cli, so I resisted the temptation to change to "they".
4.  On log.js, I note the [ngbp] prefix again.  It'd be nice to factor this out.  Is there any reason we couldn't call this module from ngbp-cli?  I think this may be your comment that you've written a log module but haven't used it everywhere.
5.  In ngbp.js I can see we're making the LOG.verbose globally available.  Any reason we're not making the non-verbose logging global - seems like most modules will need to create a LOG object anyway if we don't, so making the verbose global has little benefit?

**Comment by joshdmiller** [comment]
Again, thanks for looking at these!

> cli.js line 136 or thereabouts. I can't work out what cb() is

It stands for "callback". :-) The [`async.each`](https://github.com/caolan/async#each) method calls the method given as the second argument for each item in the array **in parallel**, calling the third argument when all of functions are done. Because the function callback is asynchronous, each callback needs to let the iterator know when it's done, which it does by passing another callback function to the callback (`cb`). It's intended for asynchronous operations like file reads. That sounded a lot more confusing than it really is. haha

I could (should?) have called it "callback".

> For config.js, it feels like we might want to have new config values associated with a particular plugin/contrib

Because we're using Grunt to run tasks, there is only one config object (accessible through `grunt.config`). Also, since tasks need to share information (like globs), we need one central config anyway. The `ngbp.config` module only gives the default values, which can be overwritten through the `ngbp` property of the Grunt config, e.g.:

``` js
// in the Gruntfile.js
grunt.initConfig({
  ngbp: {
    globs: {
      vendor: {
        js: [ "merge/this/path/with/the/default" ]
      }
    }
  }
});
```

So the configuration is already "pluggable". Also, individual plugins can register new globs and define tasks, all of which merge their configurations into the global config. In fact, the `ngbp.task.create` method takes two arguments: the name of the task, and its config object. The config object gets directly merged into the global config (with the Gruntfile taking precedence).

At some point, we may want to allow plugins to directly add config values, rather than just indirectly. But my initial thought is that this should be avoided if possible because we want to encourage plugins to exist independently of and uncoupled from others, except in explicitly defined ways (like globs).

> I resisted the temptation to change colors to colours. :-). I was mildly amused at the comment designating our users as "she" in cli, so I resisted the temptation to change to "they".

ha! Well, I'm no chauvinist. Also, though I am American, my undergraduate education was British, so "colours" wouldn't bother me in the least.

> On log.js, I note the [ngbp] prefix again. It'd be nice to factor this out.

Well, it's factored out in the sense that it exists only in one place, so it follows a DRY approach. What's the advantage of placing it in a constant? Why would we want to change it?

> In ngbp.js I can see we're making the LOG.verbose globally available. Any reason we're not making the non-verbose logging global - seems like most modules will need to create a LOG object anyway if we don't, so making the verbose global has little benefit?

The `log` module already is made globally available through the `nRequire` method, but `verbose` is not so I added it explicitly. The `log` module isn't an object that gets created - every single module running in the same context will use exactly the same `log` module because node modules are essentially singletons. This module is used heavily in the `cli` module already, but most of the other modules still use `grunt.log` and `grunt.verbose`, which we'll need to switch to the new one.

> Is there any reason we couldn't call this module from ngbp-cli?

We can't call it from `ngbp-cli` because `ngbp-cli` has to check if `ngbp` is installed before it runs; we can't include the log module of a yet-to-be-installed module. :-)

**Comment by PaulL1** [comment]
OK, all makes sense.

On the [ngbp] I was imagining getting to a single global definition of that, allowing the option to change it later.  It's currently defined in both the log.js and ngbp-cli.  But two isn't a large number, wouldn't be that hard to remember to change both, as you note ngbp-cli is already a special case.

**Comment by joshdmiller** [comment]
@PaulL1 I see what you're saying now. But I don't think there's any way to share the two without placing a dependency on `ngbp` in `ngbp-cli`. We don't want to do that because, right now, the `ngbp-cli` will work with virtually _any_ change that comes to `ngbp` without having to upgrade `ngbp-cli` specifically. It also means that the same global `ngbp-cli` will work with ten different projects using ten different versions of `ngbp`.

You're right, it's code duplication, but I don't think there's a desirable way to fix it. And you're also right that two isn't a large number.

**Pull request closed without merging**
