### PR TITLE
(wip) build and compile step

### PR DESCRIPTION
**Pull request by ajoslin**
After #34 discussion.

it has some TODOs riddled here and there, but those are mostly documentation.

I also took the liberty to rename `./vendor` to `./components` and `src/components` to `src/common`.  Lemme know if you don't like those and I'll put them back :-)

### CODE REVIEW

**Comment by ajoslin** [comment]
Not sure why travis is failing .. lemme know if it works on your end.

**Comment by joshdmiller** [comment]
Holy crap you got on that fast! :-)

The build is failing because it's not finding the module `placeholders`. A quick glance of the code did not reveal why. I'll download it and take a look this evening.

Thanks!!!

**Comment by ajoslin** [comment]
dump for errors/fixes/ideas

fixes
- [x] vendor_files.css isn't copied in copy step
- [x] rename /components back to /vendor

ideas
- Newest karma uses JSON config similar to Grunt.  We could factor vendor_files out into a seperate json file and read it into both Grunt and Karma config. https://github.com/karma-runner/karma/blob/master/config.tpl.js

**Comment by mikegioia** [comment]
Hi guys - just curious as to the status of this issue. I just recently got ng-boilerplate up (and love it) but I found it far too cumbersome to have it compile after every single file save. Having the "dev/prod" mode would really make this perfect.

**Comment by ajoslin** [comment]
Updated - added docs, fixed the vendor_files bug, renamed components back to vendor.

@mikegioia This PR is very usable. Go ahead and use it:

``` sh
git clone git://github.com/ajoslin/ng-boilerplate -b v0.3-wip --recursive my-project
cd my-project
npm install
bower install
```

 Tell me if you find any bugs :D

**Comment by mikegioia** [comment]
@ajoslin thanks! I'll pull this down and test it out.

**Comment by ajoslin** [comment]
Forgot to add instructions to switch branches, fixed that :-) But you might've already figured that out.

**Comment by ctrix** [comment]
@ajoslin your build fails because main.less and variables.less still refer to the components directory even after you've switched back to vendor.

**Comment by langerc** [comment]
I had to change some things to get it working after the clone
less/font-awesome.less -> change path to @FontAwesomePath:   "../assets/fonts";

less/main.less -> change ../../components/ to ../../vendor 
less/variables.less -> change ../../components/ to ../../vendor
otherwhise the less wont compile and a weird error message without any details occure

grunt compile does what its supposed to do now, grunt watch is working as well. Grunt watch stops with the master project after i change a test so thats a big improvement already. Thank you for the nice fork

**Comment by joshdmiller** [comment]
Okay, it's been a long time coming, but I've finally merged this! Because some changes here were just reverted again and because I needed to make a few changes and to try and keep the commit tree digestible, I made these commits independently:
1. c994b0e: moves `src/components` to `src/common`
2. 97fb290: splits `build` task into `build` and `compile`

Right now, these are just on a `merge35` branch. I wanted to get some feedback before I throw it in `master`.

@ajoslin - Thanks again! Do you have any further thoughts? Did I miss anything?

**Comment by joshdmiller** [comment]
These changes have been merged to master. Yay! Thanks again, @ajoslin!

**Pull request closed without merging**
