### PR TITLE
feat(build): Add grunt-ngmin for annotation

### PR DESCRIPTION
**Pull request by ajoslin**
Unfortunately, grunt-ngmin is still in an early state right now and can't handle the fancy way ng-boilerplate does module declaration (with the `.config` `.controller` etc functions called on a seperate line from the module declaration), so it doesn't work yet.  Still, it could stay in a branch for now until ngmin matures.  Or we can be more verbose with declaration of things (it does work if we put `angular.module('module')` before every call).

### CODE REVIEW

**Comment by ajoslin** [comment]
Also, I had to patch the grunt-ngmin task.  To make it work until brian accepts [the PR](https://github.com/btford/grunt-ngmin/pull/1), run:

```
npm install git://github.com/ajoslin/grunt-ngmin
```

**Comment by ajoslin** [comment]
Aha, brian has an [issue](https://github.com/btford/ngmin/issues/11) for doing chain-syntax! :smile:

**Comment by joshdmiller** [comment]
It looks like your first PR was merged, so we just have to wait for the chain syntax. Sweet! We'll just keep this open in the meantime...

**Comment by meenie** [comment]
Any update on this?

**Comment by joshdmiller** [comment]
Landed (with minor changes) as 9c529ccb60103b50d9c655172beacb4e12c3f91d.

**Pull request closed without merging**
