### PR TITLE
prevent uglify from messing up with angular provider

### PR DESCRIPTION
**Pull request by dv336699**
As explained here:
http://stackoverflow.com/questions/17238759/angular-module-minification-bug?answertab=votes#tab-top

### CODE REVIEW

**Comment by joshdmiller** [comment]
@diego-vieira Thanks for the contribution. I don't think that SO post is inaccurate in terms of what gets mangled (see my comment there). Did you encounter a problem with the current method of `ng-min`, which ng-boilerplate uses out of the box?

**Comment by dv336699** [comment]
Hi Josh, I'm not sure if I messed up with the settings, but ng-min doesn't seems to be working as expected. Which leads me with the error "Unknown provider: aProvider <- a" on the console after compiling. So, setting mangle to false  worked just fine, again not sure if there is a issue with my code ATM. I can send it to you if you want though.

Anyway, just thought that setting mangle to false would be a wise choice.
Thanks!

**Comment by joshdmiller** [comment]
@diego-vieira It shouldn't be required - but there have been bugs in the past. Mangling reduces file transfer times, so it's a good idea overall. `ng-min` should take this:

``` js
app.controller('MainCtrl', function ($scope, $http) {});
```

And turn it into this, for which mangling doesn't matter:

``` js
app.controller('MainCtrl', [ '$scope', '$http', function ($scope, $http) {}]);
```

Can I see the service/controller definition that fails? It might be something simple - or a pernicious bug. :-)

**Comment by dv336699** [comment]
Oh well, I have disabled uglify and ng-min seems to be working as expected, no idea here what's going on here.
Below is a test from the js from the bin file.

```
]).controller('ModalTestCtrl', [
  '$scope',
  'Restangular',
  function ModalTestCtrl($scope, Restangular) {
  }
]);
```

but, it seems that the issue is with iu-bootstrap modal, I'll research more about this.

Thank josh, I'm closing this for now.

**Pull request closed without merging**
