### PR TITLE
Replace ngmin with ng-annotate

### PR DESCRIPTION
**Pull request by doubleo2**
ngmin doesn't annotate dependencies in resolves on a ui-router state and ng-annotate does. Using states is a big part of the ngbp project structure. Also, ng-annotate is faster and more robust. 

Furthermore, @btford is okay with deprecating ngmin and nominating ng-annotate as it's successor. See btford/ngmin#93, specifically https://github.com/btford/ngmin/issues/93#issuecomment-43699038

### CODE REVIEW

**Comment by vandres** [comment]
+1

**Comment by karol-f** [comment]
+1

**Comment by realyze** [comment]
+1

**Comment by mxl** [comment]
+1

**Comment by ghost** [comment]
Please merge this... +1

**Comment by philbot5000** [comment]
Yeah, this should be merged. +1

**Comment by macedigital** [comment]
+1
Just to reiterate: ngmin **does not** annotate dependencies in resolves on a ui-router state, ng-annotate does. This is a deal breaker in non-trivial applications, especially, if you're using nested states.

**Comment by crshumate** [comment]
+1

**Comment by Merott** [comment]
@doubleo2 

I'd like to merge this in, but it's already become outdated as we took too long. If you could update to `0.4.0`, I'll have it merged ASAP.

Please squash your commits too, so that there is only one commit to merge from the PR.

**Comment by doubleo2** [comment]
@Merott Sorry for not getting around to this sooner. 

Where can I find `0.4.0`? As far as I can tell `v0.3.2-release` is the latest.

At the moment my PR only has one commit, right?

**Comment by manbearwiz** [comment]
According to npm, grunt-ng-annotate is [on version 0.8.0 now](https://www.npmjs.org/package/grunt-ng-annotate).

**Comment by doubleo2** [comment]
@Merott kmb pointed out that you were referring to the version of grunt-ng-annotate. Updated the pull request with the latest (v0.8.0). Let me know if I've mixed anything up.

h/t @kmb32123

**Comment by Merott** [comment]
Thanks @doubleo2 

I have merged this in. I edited the commit message to match the `ngbp` style, which granted isn't documented as far as I know. (I'm going to change that)

I have still kept you as the author though. Thanks for contributing.

Merged: cb4578e68dff21d91f3e6cd1ef166a802fac7ebd

**Pull request closed without merging**
