### PR TITLE
Allow js files to be added to the assets directory

### PR DESCRIPTION
**Pull request by cymantic**
without them being linted or added to karma tests...

In some cases I need to load 3rd party js files into the application that aren't compiled with the rest.

These files are already minified and fail the js linting, this change means that they are excluded from the js checks and karma running

### CODE REVIEW

**Comment by joshdmiller** [comment]
Thanks for submitting this, @cymantic. I do have one question, though it may just be a misunderstanding on my part. Shouldn't the vendor code come from the `vendor/` directory? Then the existing build process should work. Or am I missing something?

**Comment by cymantic** [comment]
It's a bit of a special case, I'm loading additional javascript libraries into other frames to interact with an angular application. These libs are not part of the compiled angular ng-boilerplate.js file, but are served from the assets directory as separate minified files.

JS to be compiled into the ng-boilerplate.js application most definitely comes from the vendor directory.

Although my use case is special, I think the treatment of the files is consistent with expectation: if a js file is in the assets directory, then I would expect it to be treated as an asset and just copied to the build/compile assets directories without it  undergoing any other processing, I would expect it to be separate from the application so shouldn't go through karma testing. (Once we have protractor(?) for end to end testing that's different, but no need for unit testing of an asset)

**Comment by joshdmiller** [comment]
Only files in `src/app` and `src/common` get unit-tested. The files from `vendor/` are _included_ when unit tests are run to ensure that files that depend on them have access to them during testing.

I'm not sold yet on the idea of including JavaScript files outside the application as I don't see how they'll be used. Can you give an example where JavaScript files will be included in the application but not be referenced by the application? In your use case, it sounds like AngularJS needs to know about them; AngularJS shouldn't know anything about files in `assets/` because they can't be used in the unit tests and we should be encouraging unit testing.

**Comment by cymantic** [comment]
You're right, I don't want to include JS files that are outside the application. AngularJS shouldn't know anything about the files in `assets/`.

When I put a CSS file or an image or a PDF into the assets directory it isn't changed, CSS isn't concatenated into my application, images don't get sprited, a PDF isn't validated. 

An asset is just an asset. No processing required. Just copy the file in the build/compile.

But as of now, if I put a JS file into the assets directory, then the JSLint runs over it. It shouldn't even know about it.
Karma tries to load the JS file, it shouldn't be part of the application, so why is it being loaded as part of the tests?

These changes allow all assets to be treated equitably.

## 

In my specific case I have a library that gets loaded into a separate frame
`<iframe ng-src="{{another-url}}"></iframe>`

This frame isn't part of the angular application, but loaded from elsewhere, and needs to have some additional functionality injected into it where `$doc` is a reference to the window.document of the iframe...

```
var scripts = ['/app/assets/libs/jquery-ui-1.10.3.custom.min.js', '/app/assets/libs/colResizable-1.3.min.js'];
            angular.forEach(scripts, function (src) {
                var script = $doc.createElement('script');
                script.type = 'text/javascript';
                script.src = src;
                $doc.head.appendChild(script);
            });
```

**Comment by joshdmiller** [comment]
Alright, you win. :-)

Landed as 99b5075. Thanks, @cymantic!

**Pull request closed without merging**
