### PR TITLE
testacular is now called karma

### PR DESCRIPTION
**Pull request by a5sk4s**
Made changes to replace testacular with karma throughout the repo.

Also fixed some typos and a broken link.

### CODE REVIEW

**Comment by joshdmiller** [comment]
@a5sk4s Thanks! The CI build failed because of a config issue. I'll go ahead and pull this branch in locally and fix it and then merge this in.

**Comment by a5sk4s** [comment]
I ran the tests, but maybe the issue is because of this - it still mentions testacular

```
$ cat .travis.yml
language: node_js
node_js:
   - "0.8"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli testacular
  - npm install

script: grunt
```

Sorry about that.

**Comment by joshdmiller** [comment]
Yeah, I recently had this issue with another repo and missed the same thing when I pushed. It's no big deal. I also might swap out my custom Testacular build script for `grunt-karma` as I used it for another project and it seems to work well - one less thing to maintain...

Thanks again - I'll get this merged in the next day or so.

**Comment by a5sk4s** [comment]
Changing Chrome to PhantomJS makes the CI build pass. Is Chrome supported? Switching it back to  Firefox - don't remember why I changed it in the first place.

**Comment by nuweb** [comment]
Couldn't get this app running. 
Running grunt aborts due to warnings, this may be related to using testacular, I have Karma installed.

$cveera: ng-boilerplate: grunt
Running "clean:0" (clean) task
Cleaning "dist"...OK

Running "html2js:app" (html2js) task

Running "html2js:component" (html2js) task

Running "jshint:src" (jshint) task

> > 16 files lint free.

Running "jshint:test" (jshint) task

> > 4 files lint free.

Running "jshint:gruntfile" (jshint) task

> > 1 file lint free.

Running "jshint:globals" (jshint) task

> > 0 files lint free.

Running "test:unit" (test) task
Running cmd
Warning: Cannot read property 'stdout' of undefined Use --force to continue.

Aborted due to warnings.

**Comment by joshdmiller** [comment]
Landed as afd1f5e6de6647b32d13256d88b92ee7ce3d9656. Finally!

Thanks!!!

**Pull request closed without merging**
