### PR TITLE
fixed vendor CSS deploy issue

### PR DESCRIPTION
**Pull request by garris**
CSS files listed in /build.config.js > vendor_files.css are now correctly deployed to /build/vendor/[dirName...] as expected.

### CODE REVIEW

**Comment by garris** [comment]
The same issue occurred when doing a compile.  The index.html was pointing to vendor css files that were not copied by grunt.

**Comment by garris** [comment]
I see now that this was partially addressed in **removed vendor css from index tasks #245**.   However,  I took a different approach.   It appears the intention was for vendor css files to have been preserved and copied to the build & and bin directories -- so, I have implemented the copy pass for css files.

**Comment by bretongoers** [comment]
Thanks for this fix. I pulled it into my project and it works great - total lifesaver when using several open source components that rely on pre-built CSS. Hopefully it's incorporated!

**Comment by jrzerr** [comment]
@garris I had the exact same problem, vendor CSS not being included in my production site in `bin/` from running `grunt`. I used your commits to patch my project and is working great for me using production site in `bin/` and also just as importantly also works on dev site with `grunt watch`.  Thanks...

**Comment by garris** [comment]
Really glad I could help.  Cheers!

**Comment by Merott** [comment]
@garris 

Thanks for the fix.

If you could squash the first two of the commits in this PR on a feature branch and submit a new clean PR, I'll have it merged in.

**Comment by garris** [comment]
Ok.  Please see pull request #336  -- not sure where the request should be merged _to_.  Maybe master?  Any case it points to the 0.3.2 branch now.

**Pull request closed without merging**
