### PR TITLE
Tweaked Gruntfile.js so that everywhere it refers to the "dist" dir it uses the variable.

### PR DESCRIPTION
**Pull request by mtlewis**
Before, there were a few spots where the directory "dist" was hardcoded, so if you wanted to change the build output directory, you had to fiddle with those too.

### CODE REVIEW

**Comment by joshdmiller** [comment]
Well, crap - how did I miss that? Thanks, @mtlewis! I'll get this merged today.

**Comment by nikolawannabe** [comment]
I've applied these fixes to mine and removed all references to dist, but I still have a problem with the watcher task:

```
WARN [watcher]: Pattern "/home/me/src/js/dist/tmp/**/*.js" does not match any file.
```

and my build output directory is not in this location, so it shouldn't be trying to look there.  Any hints what might be causing this?

**Comment by joshdmiller** [comment]
@nikolawannabe This is a different problem. Can you link to your gruntfile?

**Comment by nikolawannabe** [comment]
@joshdmiller Here you go: http://pastebin.com/zVNzeFiN

**Comment by joshdmiller** [comment]
That's being caused by the reference to `src.tpljs` in the `jshint` watch task. It's looking for templates but you may not have any. Do the templates exist there or in a different folder?

**Comment by nikolawannabe** [comment]
I do have templates (and this task worked fine before changing the build
output directory).  Their tmp files are outputted to the location I
specified in the distdir on line 32/tmp, and they are correctly concatted
into my package's .js file.

On Mon, Jun 17, 2013 at 12:24 PM, Josh D Miller notifications@github.comwrote:

> That's being caused by the reference to src.tpljs in the jshint watch
> task. It's looking for templates but you may not have any. Do the templates
> exist there or in a different folder?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshdmiller/ng-boilerplate/pull/36#issuecomment-19568287
> .

## 

--Case
(Old Habits Die Hard)

**Comment by joshdmiller** [comment]
@nikolawannabe I was trying to help from my mobile before so I probably missed it. But I went to look again at your pastebin and it's no longer there. Did you solve your issue?

**Comment by joshdmiller** [comment]
@mtlewis Thanks for this fix! Landed as 03fdf4f.

@nikolawannabe If you're still having your issue, can you open a new issue?

**Pull request closed without merging**
