### PR TITLE
Fixes #278, glyphicon fonts not copied during build

### LINKED ISSUE #278: vendor_assets not copied during build
When trying to use Glyphicons they do not appear, and I see this in the console:

```
GET file:///{path to build}/build/fonts/glyphicons-halflings-regular.woff net::ERR_FILE_NOT_FOUND 
```

So I am trying to copy Glyphicons font assets from vendor/bootrap/dist/fonts to build/vendor/bootstrap/dist/fonts.  So I updated build.config.js to:

``` javascript
 vendor_files: {
    js: [
      'vendor/angular/angular.js',
      'vendor/angular-bootstrap/ui-bootstrap-tpls.min.js',
      'vendor/placeholders/angular-placeholders-0.0.1-SNAPSHOT.min.js',
      'vendor/angular-ui-router/release/angular-ui-router.js',
      'vendor/angular-ui-utils/modules/route/route.js'
    ],
    css: [
    ],
   // add glyhpicons font paths here
    assets: [
      'vendor/boostrap/dist/fonts/glyphicons-halflings-regular.eot',
      'vendor/boostrap/dist/fonts/glyphicons-halflings-regular.svg',
      'vendor/boostrap/dist/fonts/glyphicons-halflings-regular.ttf',
      'vendor/boostrap/dist/fonts/glyphicons-halflings-regular.woff'
    ]
  }
```

However output from grunt watch shows the task does nothing:

```
Running "copy:build_vendor_assets" (copy) task

Running "copy:build_appjs" (copy) task
Copied 4 files
```

If this were to work I would then have added the path override to variables.less as:

``` less
 @icon-font-path: "../vendor/bootstrap/dist/fonts/";
```

So this is not working as expected, please advise if I am not understanding the usage correctly.

### PR DESCRIPTION
**Pull request by RoboSparrow**
fix(build):  fiixes issue #278. Maybe in the next iteration this can be done more elegantly via Gruntfile.js.

### CODE REVIEW

**Comment by saibotsivad** [comment]
Hey there @RoboSparrow , sorry for the long delay. We are attempting to get ngbp back up to speed, and I'd like to merge yours in. Could you update it your PR to follow the [CONTRIBUTING.md](https://github.com/ngbp/ngbp/blob/v0.3.2-release/CONTRIBUTING.md) guide?

**Comment by esco** [comment]
:+1:

**Comment by RoboSparrow** [comment]
@saibotsivad. Updated PR and adjusted commit msg. Ok now?

**Comment by Merott** [comment]
@RoboSparrow You'd need to change the git commit message. It might be easier to first rebase your current branch on top of the latest master. Then amend your commit message (currently it's **`Fixes #278, glyphicon fonts not copied during build`**) and do a force-push.

**Comment by RoboSparrow** [comment]
Sorry for the late reply. I was flat out with work. @Merott. Thanks for the tip. Still, I will close this PR and commit a new one as the solution itself can be improved.

**Pull request closed without merging**
