### PR TITLE
docs(readme): add a note about PR style rules

### PR DESCRIPTION
**Pull request by Merott**
@joshdmiller 

Please review. This should make it easier for others to submit good quality PRs that will be merged in.

### CODE REVIEW

**Comment by joshdmiller** [comment]
This is great. If you put it in a `CONTRIBUTING.md` doc in the root of the project, though, GitHub will automatically include a note at the top of the page when someone creates an issue or PR. Let me see if I have one around here...

**Comment by Merott** [comment]
That's cool, didn't know about that!

Done.

**Comment by joshdmiller** [comment]
@Merott Perfect! We can always add to it over time.

**Comment by Merott** [comment]
@joshdmiller I'll go ahead and merge it in then.

**Pull request merged**
