### PR TITLE
(docs) npm -g install > npm install -g

### PR DESCRIPTION
**Pull request by megatolya**
`npm -g install` will not install anything. Fixed to `npm install -g`

### CODE REVIEW

**Comment by joshdmiller** [comment]
This works just fine for me; what platform are you on?

**Comment by megatolya** [comment]
mac

**Comment by mikedevita** [comment]
works fine for me too, I always specify it as `npm -g install`

**Comment by pavanpaik** [comment]
Works fine for me too on my windows machine. I always give it as npm -g install

**Comment by megatolya** [comment]
Cannot reproduce it now. I think it was a problem of old npm versions

**Pull request closed without merging**
