### PR TITLE
Fixed copy of assets in delta config

### PR DESCRIPTION
**Pull request by iambrandonn**
Commit 29502bff8eb649501945aef37fe50d81c36151ba broke the copying of assets from the delta task.
Instead of doing copy:build_assets, we need to do copy:build_app_assets and copy:build_vendor_assets.

### CODE REVIEW

**Comment by joshdmiller** [comment]
Thanks for submitting this. How did you find it? Did you have a use case for changing asset files?

**Comment by iambrandonn** [comment]
I was customizing things a bit and moved a few files which is what triggered it.  I wouldn't normally have a use case for it though.

**Comment by joshdmiller** [comment]
Well, nonetheless I'll happily implement it. Thanks for the PR!

**Comment by joshdmiller** [comment]
Merged. Thanks!

**Pull request closed without merging**
